In [14]:
# Cell 1: Import necessary libraries and functions from extract.py

import numpy as np
from scipy import sparse
from extract import Graph, extract_node_identity  # Import classes and functions


In [15]:

# Cell 2: Define Graphs for Testing

# Define an adjacency matrix for Graph 1
adj_matrix_1 = sparse.csr_matrix(np.array([
    [0, 1, 1, 0],
    [1, 0, 1, 1],
    [1, 1, 0, 1],
    [0, 1, 1, 0]
]))

# Define an adjacency matrix for Graph 2
adj_matrix_2 = sparse.csr_matrix(np.array([
    [0, 1, 0, 1],
    [1, 0, 1, 0],
    [0, 1, 0, 1],
    [1, 0, 1, 0]
]))

# Initialize the graph objects
graph1 = Graph(adj_matrix_1)
graph2 = Graph(adj_matrix_2)


In [16]:
# Cell 3: Set Parameters and Extract Features

# Set parameters
K = 2  # Maximum hop distance
delta = 0.5  # Discount factor

# Extract node identities for both graphs
node_identities_1 = extract_node_identity(graph1, K, delta)
node_identities_2 = extract_node_identity(graph2, K, delta)

print("Node Identities for Graph 1:\n", node_identities_1)
print("\nNode Identities for Graph 2:\n", node_identities_2)


Node Identities for Graph 1:
 [[0.  0.  0.  2.  0.  0.  0.5 1. ]
 [0.  0.  2.  1.  0.  0.  1.  0.5]
 [0.  0.  2.  1.  0.  0.  1.  0.5]
 [0.  0.  0.  2.  0.  0.  0.5 1. ]]

Node Identities for Graph 2:
 [[0.  0.  2.  0.  0.  1.5]
 [0.  0.  2.  0.  0.  1.5]
 [0.  0.  2.  0.  0.  1.5]
 [0.  0.  2.  0.  0.  1.5]]


In [17]:
# Cell 4: Display the Results in a Table

import pandas as pd

# Convert node identity arrays to DataFrames for easy viewing
df_graph1 = pd.DataFrame(node_identities_1, columns=[f"Feature_{i}" for i in range(node_identities_1.shape[1])])
df_graph2 = pd.DataFrame(node_identities_2, columns=[f"Feature_{i}" for i in range(node_identities_2.shape[1])])

print("Node Identities for Graph 1:")
display(df_graph1)

print("Node Identities for Graph 2:")
display(df_graph2)


Node Identities for Graph 1:


Feature_0  Feature_1  Feature_2  Feature_3  Feature_4  Feature_5  \
0        0.0        0.0        0.0        2.0        0.0        0.0   
1        0.0        0.0        2.0        1.0        0.0        0.0   
2        0.0        0.0        2.0        1.0        0.0        0.0   
3        0.0        0.0        0.0        2.0        0.0        0.0   

   Feature_6  Feature_7  
0        0.5        1.0  
1        1.0        0.5  
2        1.0        0.5  
3        0.5        1.0

Node Identities for Graph 2:


Feature_0  Feature_1  Feature_2  Feature_3  Feature_4  Feature_5
0        0.0        0.0        2.0        0.0        0.0        1.5
1        0.0        0.0        2.0        0.0        0.0        1.5
2        0.0        0.0        2.0        0.0        0.0        1.5
3        0.0        0.0        2.0        0.0        0.0        1.5