# Import Section

In [1]:
import networkx as nx
import pandas as pd
import os
from scipy import sparse
from aligning import *
from extract import *
from representation import *
from configuration import RepMethod

# Read in the graphs for the first analysis

We are comparing the database of Deezer users in Romania and Hungary.

In [15]:
df2=pd.read_csv("RO_edges.csv")

In [17]:
df=pd.read_csv("HU_edges.csv")

# Extract the features
Step 1 of regal


In [20]:
G = nx.from_pandas_edgelist(df, source='node_1', target='node_2')

In [21]:
G2= nx.from_pandas_edgelist(df2, source='node_1', target='node_2')

In [23]:
adj_matrix=nx.adjacency_matrix(G)
adj_matrix2 = nx.adjacency_matrix(G2)

In [25]:
adj_matrix_combined = sparse.block_diag([adj_matrix, adj_matrix2])

# Initialize the graph objects
graph1 = Graph(adj_matrix)
graph2 = Graph(adj_matrix2)
graph3 = Graph(adj_matrix_combined)

I commented out the node identities 1 and 2 to lower runtime


In [28]:
K = 2  # Maximum hop distance
delta = 0.5  # Discount factor

# Extract node identities for both graphs
#node_identities_1 = extract_node_identity(graph1, K, delta)
#node_identities_2 = extract_node_identity(graph2, K, delta)
node_identities_3 = extract_node_identity(graph3, K, delta)

#print("Node Identities for Graph 1:\n", node_identities_1)
#print("\nNode Identities for Graph 2:\n", node_identities_2)
print("\nNode Identities for Graph 3:\n", node_identities_3)


Node Identities for Graph 3:
 [[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


# Get the representations of the graphs

In [31]:
rep_method = RepMethod(max_layer=2)
print('Number of landmark nodes:', rep_method.p)


Number of landmark nodes: None


In [32]:
get_number_of_landmarks(graph3, rep_method)
print(rep_method.p)

164


In [33]:
landmarks = get_random_landmarks(graph3, rep_method)
print(landmarks)

[17990 33676 10263 75971 16864 71567 80912 74787 26535  9860 64507 56182
 21460 82676 76328 49099 74657 21076 56290 54192 79016 76013 51012  5756
  3301 41486 29967  4526 64809 42670 61562 64449 36613  5550 69753 30450
 88673 48556 40178 70982 56012 28734 84442  5925 37365  8659 13748  9150
 48767 64683 22526 63239 23846 87394 41996 16307 82443 16970 61690 54469
 20124 68340  1711 77421  6501 82977 63394  6033 67205 46640  7541 19992
 39236  1535 25675 81272 75403 57533 67902 73197 37312 15017  9559 84980
 28052 66566 66618 55409 32698 36858 20626 39013 58546 14966  3899 76940
 43083 81741 42454 40077 34883 48598 17289 61234 21086 79031  4378 15285
 75528 41447 81664  3182 87127 23271 58484 53590 56326 25047 75198 33840
  7069 55650 45183 87218 44781 61128 82896 56373 66711 19319 35628 43750
 12443  8688 46037 42740 37335 66433 14726 75057 10000 13087  4147 31157
 73247 48950 66530  8349 74515 87083 67239 49233  1410 27808 87496 70640
 46390 84566 67198  6908 25491 73335 85251 40063]


In [34]:
C = compute_C_matrix(node_identities_3, landmarks)
(f'Shape of C: {len(C)} x {len(C[0])}')
print('C:')
print(C)

C:
[[1.29958143e-024 7.28129018e-033 1.60381089e-028 ... 4.07955867e-041
  2.17052201e-029 4.76403211e-101]
 [1.87952882e-012 1.71390843e-015 2.31952283e-016 ... 4.65888615e-015
  9.35762297e-014 1.92194773e-098]
 [2.78946809e-010 4.65888615e-015 2.54366565e-013 ... 2.78946809e-010
  7.58256043e-010 3.38030668e-123]
 ...
 [1.38879439e-011 9.35762297e-014 2.31952283e-016 ... 6.73794700e-003
  6.14421235e-006 3.90365393e-140]
 [2.54366565e-013 9.35762297e-014 3.13913279e-017 ... 3.67879441e-001
  8.31528719e-007 7.14979157e-142]
 [3.77513454e-011 4.65888615e-015 1.15482242e-017 ... 3.35462628e-004
  3.05902321e-007 7.84069851e-139]]


In [35]:
representations_1, representations_2 = compute_representation(C, landmarks, adj_matrix.shape[0])
print('Representations of nodes from first graph:')
print(representations_1)
representations_1= np.nan_to_num(representations_1, nan=0)
representations_2= np.nan_to_num(representations_2, nan=0)

Representations of nodes from first graph:
[[-9.08563624e-13 -9.62075620e-13  2.93953424e-11 ...  5.38881856e-13
  -1.87044235e-26  9.46306569e-26]
 [ 5.57212829e-06  3.06657581e-06 -1.22482651e-05 ...  4.81005433e-06
  -1.17684302e-24 -2.51675083e-25]
 [-1.00128301e-03 -2.50086135e-05  5.76052206e-04 ...  1.20824276e-03
  -2.76944465e-24  3.66126019e-24]
 ...
 [-1.44905463e-01  8.51030397e-02 -9.94035323e-03 ...  8.96406684e-01
   1.95686270e-24  4.24678479e-24]
 [-1.60667698e-02 -2.62665133e-04  1.24732031e-02 ...  1.40475190e-01
   2.08523174e-25  3.89093920e-26]
 [ 7.63574115e-02 -6.06198858e-01 -2.17149988e-01 ...  4.27968764e-01
   7.26524174e-25  2.23192706e-24]]


C:\Users\nps0027\Downloads\representation.py:74: RuntimeWarning: divide by zero encountered in divide
  Y_twiddle = Y_twiddle / np.linalg.norm(Y_twiddle, axis=1).reshape(Y_twiddle.shape[0], 1) # Normalization of rows
C:\Users\nps0027\Downloads\representation.py:74: RuntimeWarning: invalid value encountered in divide
  Y_twiddle = Y_twiddle / np.linalg.norm(Y_twiddle, axis=1).reshape(Y_twiddle.shape[0], 1) # Normalization of rows


# Calculate Similarity Matrix
Similarity for the alignment of Graph 1 and 2, showing the 3 most similar nodes. 

In [37]:
similarity_matrix = get_similarity_matrix(representations_1, representations_2, 3)
print(similarity_matrix)

C:\ProgramData\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\ProgramData\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


  (0, 8306)	0.9543844291838592
  (0, 11472)	0.9523321303424711
  (0, 2034)	0.951952291332164
  (1, 29719)	0.9453015440336867
  (1, 20105)	0.9452474129358718
  (1, 8111)	0.9452109238476236
  (2, 37508)	0.9692400066541615
  (2, 1625)	0.9666039605194034
  (2, 9306)	0.966576561917957
  (3, 22278)	0.9913392204469409
  (3, 12790)	0.9912850712906756
  (3, 17956)	0.9898027553553443
  (4, 7690)	0.9530120863548616
  (4, 11691)	0.9506533988332544
  (4, 18041)	0.9481328444958254
  (5, 2575)	0.9871560970840966
  (5, 17859)	0.9865347527722774
  (5, 621)	0.9855335742682437
  (6, 322)	0.9904727009092665
  (6, 23767)	0.9806142349103905
  (6, 31637)	0.956901154954738
  (7, 11857)	0.9839128726695014
  (7, 24498)	0.9555623153458805
  (7, 28554)	0.8948736204783071
  (8, 496)	0.999980871172973
  :	:
  (47529, 1407)	1.0
  (47530, 11635)	1.0
  (47530, 15437)	1.0
  (47530, 20948)	1.0
  (47531, 13949)	0.9044208564113484
  (47531, 4196)	0.9044208564113484
  (47531, 710)	0.9044208564113484
  (47532, 21550)	1.0
  

# Performance Analysis
## Helper Functions
Function to generate a permutation of the adjacency matrix

In [3]:
import numpy as np
import networkx as nx

def generate_noisy_adjacency(A, ps=0.1, seed=None):
    """
    Generate a permuted and noisy adjacency matrix A'.

    Parameters:
    - A (np.ndarray): Original adjacency matrix (square and symmetric for undirected networks).
    - ps (float): Probability of removing an edge as noise (0 ≤ ps ≤ 1).
    - seed (int): Random seed for reproducibility.

    Returns:
    - A_prime (np.ndarray): Noisy permuted adjacency matrix.
    - P (np.ndarray): Permutation matrix used for reordering.
    """
    np.random.seed(seed)
    n = A.shape[0]

    # Step 1: Create a random permutation matrix P
    perm = np.random.permutation(n)
    P = np.eye(n)[perm]
    # Step 2: Compute the permuted adjacency matrix A' = PAP^T
    A_prime = P @ A @ P.T

    # Step 3: Add structural noise by removing edges with probability ps
    G = nx.from_numpy_array(A_prime)  # Convert to a NetworkX graph
    edges = list(G.edges)  # Get the initial list of edges
    num_edges_to_remove = int(ps * len(edges))

    # Randomly remove edges, ensuring the graph stays connected
    removed_edges = 0
    while removed_edges < num_edges_to_remove:
        # Refresh the list of edges to avoid KeyError
        edges = list(G.edges)
        
        if len(edges) == 0:
            break  # Stop if no more edges are left to remove
        
        edge_to_remove = edges[np.random.randint(len(edges))]
        
        # Remove the edge
        G.remove_edge(*edge_to_remove)
        
        # Ensure the graph is still connected after removing the edge
        if nx.is_connected(G):
            removed_edges += 1
        else:
            G.add_edge(*edge_to_remove)  # Restore edge if disconnection occurs

    # Convert back to adjacency matrix
    A_prime = nx.to_numpy_array(G, dtype=int)

    return A_prime, P


Function to convert the similarity matrix to a permutation matrix

In [5]:
import numpy as np
from scipy.sparse import coo_matrix

def similarity_to_permutation(similarity_matrix):
    """
    Convert the similarity matrix (sparse format) into a permutation matrix in sparse format.
    
    Args:
    similarity_matrix: A sparse matrix of similarity scores, in COO format.
    
    Returns:
    A sparse permutation matrix (COO format).
    """
    # Get the number of rows and columns
    n_rows, n_cols = similarity_matrix.shape
    
    # Lists to store the row, column indices, and values for the permutation matrix
    perm_rows = []
    perm_cols = []
    perm_data = []
    
    # Iterate through each row and find the index of the maximum similarity value
    for i in range(n_rows):
        # Get the row's non-zero entries (stored as (index, value) pairs)
        row_data = similarity_matrix.getrow(i)  # Sparse row
        
        # Find the index of the maximum similarity score for the current row
        if row_data.nnz > 0:  # Check if the row is not empty
            best_match_idx = row_data.argmax()  # Find index of the max value in sparse row
            perm_rows.append(i)
            perm_cols.append(best_match_idx)
            perm_data.append(1)  # This is a permutation matrix, so value is always 1
    
    # Create a sparse matrix in COO format from the row, column indices and data
    permutation_matrix_sparse = coo_matrix((perm_data, (perm_rows, perm_cols)), shape=(n_rows, n_cols))
    
    return permutation_matrix_sparse



In [ ]:
import numpy as np
 
def evaluate_alignment(P, P_hat):
    """
    Evaluate the accuracy of the recovered alignment.
 
    Parameters:
    - P (np.ndarray): Ground-truth permutation matrix.
    - P_hat (np.ndarray): Recovered permutation matrix.
 
    Returns:
    - accuracy (float): Fraction of correctly aligned nodes.
    - hamming_distance (int): Number of differing entries between P and P_hat.
    """
    n = P.shape[0]
    print(n)
    # Compute the permutations (row indices of the 1's)
    correct_permutation = np.argmax(P, axis=1)
    predicted_permutation = np.argmax(P_hat, axis=1)
    # Accuracy as fraction of correct permutations
    correct_matches = np.sum(correct_permutation == predicted_permutation)
    print(correct_matches)
    accuracy = correct_matches / n
 
    # Hamming distance: number of differing entries between P and P_hat
    hamming_distance = np.sum(P != P_hat)/(n*P.shape[1])
 
    return accuracy, hamming_distance
 

Function to evaluate the alignment qualities

In [11]:
collected_accuracies = [0 for _ in range(100)]
collected_hamming = [0 for _ in range(100)]
K = 2  # Maximum hop distance
delta = 0.5  # Discount factor
for i in range(100): 
   
    # Create a 100x100 matrix with random 0s and 1s
    n = np.random.randint(100,501)
    matrix = np.random.randint(2, size=(n, n))
    A_hat, P_ground = generate_noisy_adjacency(matrix)
    matrix = sparse.csr_matrix(matrix)
    A_hat_t=  sparse.csr_matrix(A_hat)
    P_hat = sparse.csr_matrix(P_ground)
    adj_matrix_combined = sparse.block_diag([matrix, A_hat_t])
    graph = Graph(adj_matrix_combined)
    node_identities = extract_node_identity(graph, K, delta)
    rep_method = RepMethod(max_layer=2)
    get_number_of_landmarks(graph, rep_method)
    landmarks = get_random_landmarks(graph, rep_method)
    C = compute_C_matrix(node_identities, landmarks)
    representations_1, representations_2 = compute_representation(C, landmarks, A_hat_t.shape[0])
    representations_1= np.nan_to_num(representations_1, nan=0)
    representations_2= np.nan_to_num(representations_2, nan=0)
    similarity_matrix = get_similarity_matrix(representations_1, representations_2, 3)
    P_align = similarity_to_permutation(similarity_matrix)
    accuracy, hamming_distance = evaluate_alignment(P_align, P_hat )
    collected_accuracies[i]=accuracy
    collected_hamming[i]=hamming_distance

290
2
309
1
202
0
147
1
392
1
473
2
482
1
387
1
167
3
497
1
318
1
304
1
404
0
424
0
182
4
376
0
272
0
182
2
476
0
206
1
314
1
441
1
395
1
163
1
100
1
151
2
115
1
342
2
210
2
269
1
165
0
344
1
118
1
236
1
134
1
333
0
375
0
106
3
446
1
189
1
384
1
205
0
214
1
236
0
401
0
497
2
426
0
241
1
301
2
140
3
398
4
257
0
223
3
113
2
470
1
328
0
456
0
298
4
247
2
227
0
233
0
490
1
295
0
396
0
333
0
231
0
454
0
238
0
413
0
254
2
468
1
411
1
382
0
247
0
377
1
241
1
159
1
380
3
274
2
411
1
130
1
478
0
337
0
431
0
121
3
253
2
459
1
232
0
428
0
339
2
128
1
425
0
223
1
400
3
217
1
137
1
240
1
287
1
129
1
329
0


In [59]:
np.mean(collected_accuracies)

0.0046582366763398666

In [61]:
np.mean(collected_hamming)

0.008001182834277996